"""add lead source and address

Revision ID: 092fd9762332
Revises: 
Create Date: 2026-05-22 16:40:13.071725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092fd9762332'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('assigned_employee', sa.String(), nullable=False),
    sa.Column('demo_date', sa.Date(), nullable=False),
    sa.Column('demo_time', sa.Time(), nullable=False),
    sa.Column('demo_feedback', sa.String(), nullable=True),
    sa.Column('meeting_notes', sa.String(), nullable=True),
    sa.Column('demo_status', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('created_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demos_id'), 'demos', ['id'], unique=False)
    op.add_column('clients', sa.Column('lead_source', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'lead_source')
    op.drop_index(op.f('ix_demos_id'), table_name='demos')
    op.drop_table('demos')
    # ### end Alembic commands ###
