"""updates all the databse 

Revision ID: 49fdc9640c3e
Revises: 65744302492d
Create Date: 2026-05-26 15:38:10.384139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49fdc9640c3e'
down_revision: Union[str, Sequence[str], None] = '65744302492d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reminder_date', sa.Date(), nullable=True),
    sa.Column('reminder_time', sa.Time(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.add_column('clients', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['created_by'], ['id'])
    op.add_column('deals', sa.Column('deal_owner_id', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('deals', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('deals', sa.Column('renewal_reminder_date', sa.Date(), nullable=True))
    op.add_column('deals', sa.Column('renewal_status', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('deals', 'deal_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('deals', 'software_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('deals', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_foreign_key(None, 'deals', 'users', ['deal_owner_id'], ['id'])
    op.drop_column('deals', 'contact_person_name')
    op.drop_column('deals', 'closing_date')
    op.drop_column('deals', 'deal_person_name')
    op.drop_column('deals', 'description')
    op.add_column('demos', sa.Column('assigned_employee_id', sa.Integer(), nullable=True))
    op.add_column('demos', sa.Column('demo_installed', sa.String(), nullable=True))
    op.add_column('demos', sa.Column('installation_date', sa.Date(), nullable=True))
    op.add_column('demos', sa.Column('trial_days', sa.Integer(), nullable=True))
    op.add_column('demos', sa.Column('trial_expiry_date', sa.Date(), nullable=True))
    op.add_column('demos', sa.Column('trial_status', sa.String(), nullable=True))
    op.alter_column('demos', 'demo_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('demos', 'demo_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('demos', 'demo_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'demos', 'users', ['assigned_employee_id'], ['id'])
    op.drop_column('demos', 'assigned_employee')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('demos', sa.Column('assigned_employee', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'demos', type_='foreignkey')
    op.alter_column('demos', 'demo_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('demos', 'demo_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('demos', 'demo_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('demos', 'trial_status')
    op.drop_column('demos', 'trial_expiry_date')
    op.drop_column('demos', 'trial_days')
    op.drop_column('demos', 'installation_date')
    op.drop_column('demos', 'demo_installed')
    op.drop_column('demos', 'assigned_employee_id')
    op.add_column('deals', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('deal_person_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('deals', sa.Column('closing_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('contact_person_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.alter_column('deals', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('deals', 'software_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('deals', 'deal_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('deals', 'notes')
    op.drop_column('deals', 'renewal_status')
    op.drop_column('deals', 'renewal_reminder_date')
    op.drop_column('deals', 'end_date')
    op.drop_column('deals', 'start_date')
    op.drop_column('deals', 'deal_owner_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'created_by')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
