"""add lead source and address

Revision ID: 8f196089312f
Revises: 092fd9762332
Create Date: 2026-05-22 16:49:52.540958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f196089312f'
down_revision: Union[str, Sequence[str], None] = '092fd9762332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_logs', 'lead_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('lead_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
