"""initial crm setup

Revision ID: d34c75ac72a9
Revises: 
Create Date: 2026-05-26 17:14:26.927663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34c75ac72a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('title', sa.String(), nullable=False))
    op.add_column('reminders', sa.Column('description', sa.String(), nullable=True))
    op.add_column('reminders', sa.Column('created_date', sa.Date(), nullable=True))
    op.alter_column('reminders', 'reminder_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('reminders', 'note')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('reminders', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('reminders', 'reminder_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('reminders', 'created_date')
    op.drop_column('reminders', 'description')
    op.drop_column('reminders', 'title')
    # ### end Alembic commands ###
