"""add demo location

Revision ID: dee3c4fdeb92
Revises: 8f196089312f
Create Date: 2026-05-25 14:07:44.439464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee3c4fdeb92'
down_revision: Union[str, Sequence[str], None] = '8f196089312f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demos', sa.Column('demo_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demos', 'demo_location')
    # ### end Alembic commands ###
